### ISSUE TITLE
MOX-reactor heat pipe sprite alignment problems

### ISSUE THREAD

**Issue by CaveJohnson376** [JohnTheCoolingFan/PlutoniumEnergy#26]
![image](https://user-images.githubusercontent.com/33164023/79622137-76838c00-812f-11ea-8b3d-ca3a3a878376.png)

**Comment by CaveJohnson376** [comment]
Fixed in https://github.com/JohnTheCoolingFan/PlutoniumEnergy/commit/d1af317586398812a1ad5e7900c7c175daf4495a

**Comment by JohnTheCoolingFan** [comment]
![image](https://user-images.githubusercontent.com/43478602/148137124-07c8e10e-c6ad-44b5-9f93-33fc12eb6581.png)

**Comment by JohnTheCoolingFan** [comment]
Better image
![image](https://user-images.githubusercontent.com/43478602/148137156-4f02dc55-ea2a-4f5c-acd1-f77c0e7f90e7.png)

**Comment by JohnTheCoolingFan** [comment]
Also
![image](https://user-images.githubusercontent.com/43478602/148137613-989d598a-910e-4899-9ba8-a227b42f0400.png)

**Comment by JohnTheCoolingFan** [comment]
Also, heat pipe shadows are used from regular nuclear reactor and don't match with MOX reactor...

**Comment by JohnTheCoolingFan** [comment]
Also, heat picture is very shrunk for some reason
![image](https://user-images.githubusercontent.com/43478602/148207532-ed1091ba-0401-40dc-a3b7-515d6a910d1a.png)

**Comment by JohnTheCoolingFan** [comment]
Shadows and glow picture scale is now fixed

**Comment by JohnTheCoolingFan** [comment]
All visual slignment issues were fixed by c2696e0
