### ISSUE TITLE
Code not found

### ISSUE THREAD

**Issue by Am4iK77** [JohnTheCoolingFan/PlutoniumEnergy#70]
Hi.

I've been trying to install this mod but this is what it says to me:
<img width="733" alt="Screenshot 2023-01-20 at 12 01 13" src="https://user-images.githubusercontent.com/123153155/213645932-0889d7f5-9ddf-4c36-9720-6e27a43da354.png">

Im playing on MacBook Air M1

**Comment by JohnTheCoolingFan** [comment]
This is a problem with Advanced Atomic, not Plutonium Energy.
