### ISSUE TITLE
Working toward better IR3 support

### ISSUE THREAD

**Issue by 0n0w1c** [JohnTheCoolingFan/PlutoniumEnergy#81]
Edit: Never mind. I am unable to recreate the issue, that I obviously imaged existed.

Would you prefer to keep the IR2 support as is? Or would you prefer I convert the support to IR3?
IR2 has been deprecated.

**Comment by JohnTheCoolingFan** [comment]
Oh, if IR2 is deprecated, then yes,I think it would be better to migrate current support to IR3.
