### ISSUE TITLE
error loading mods

### ISSUE THREAD

**Issue by fedekk2014** [JohnTheCoolingFan/PlutoniumEnergy#90]
![factorio_xzq8kY7eav](https://github.com/JohnTheCoolingFan/PlutoniumEnergy/assets/65419172/8155160c-d217-4d6f-9e86-49764a32350d)

**Comment by JohnTheCoolingFan** [comment]
The problem is caused by True Nukes.

**Comment by fedekk2014** [comment]
so.. can you fix this?

**Comment by JohnTheCoolingFan** [comment]
I have reported it to the True Nukes mod author. I can take a look at it and see what got broken and try to fix, but I won't promise.

**Comment by More-Wrong** [comment]
Should be fixed in T-N now. Thanks for the fix!
