### ISSUE TITLE
IR3 support suggestions

### ISSUE THREAD

**Issue by Deadlock989** [JohnTheCoolingFan/PlutoniumEnergy#92]
Thank you for including IR3 support in your mod.

Some suggestions (based on what I'm seeing in PE 1.5.1):

- Technologies: plutonium processing tech depends on vanilla fluid handling tech, presumably because of the barrels, but IR3 does not unlock barrels in fluid handling; they are unlocked in a specialist barrelling tech instead (internal id `ir-barrelling`). Top tip: you can ask IR3 to automatically calculate the correct prerequisite techs for a technology based on the ingredients in its recipe unlocks by including a field `IR_native = true` in the technology prototype, so that if anything changes in IR3 or by a third mod, the tech will adjust itself to match; however this sometimes has unwanted side effects, especially where recipe loops are concerned, so you may prefer to set it up manually.
- Recipes: advanced nuclear fuel reprocessing and uranium solution centrifuging recipes are on the vanilla intermediates tab (re-named "complex components" in IR3) but all of the vanilla nuclear recipes in IR3 were moved to the "general processing" tab (`ir-processing`), so nuclear stuff is split across two tabs.
- Recipe issue: advanced nuclear fuel reprocessing returns 4 steel scrap per used-up uranium cell, but each cell only require 3 steel to make; so essentially this recipe can "dupe" 1 steel from nothing per fuel cell (admittedly at the cost of running nuclear infrastructure). Concrete scrap was added in IR 3.1.0 as well, but this is currently lost in PE's advanced reprocessing.
- Recipe issue: I can see that there is an "advanced nuclear fuel reprocessing (with barrelling)" recipe in FNEI, but this doesn't seem to be unlockable in IR3.

**Comment by 0n0w1c** [comment]
Thank you Deadlock989 for taking the time to review the IR3 support. I believe the first three suggestions have now been addressed as per your suggestion. However the last issue is intentional, the barrelling recipes are disabled as IR3 makes use of specialty barrelling machines.
