### ISSUE TITLE
Error loading mods

### ISSUE THREAD

**Issue by spannerman79** [JohnTheCoolingFan/PlutoniumEnergy#94]
![427520_20230817162107_1](https://github.com/JohnTheCoolingFan/PlutoniumEnergy/assets/7542384/6febba48-2924-4a70-891c-564ce95ab3e2)

Entire (current) 1.5.x releases have this issue.

Works on 1.4.14

**Comment by JohnTheCoolingFan** [comment]
Thanks for the report, I've found where the problem is, will fix it in a new update shortly.

**Comment by JohnTheCoolingFan** [comment]
1.5.3 will be released soon, please write back if it helped or not

**Comment by spannerman79** [comment]
Yeap, works now.

Thanks!
